### ISSUE TITLE
Starting hybrid implementation every N actions

### ISSUE THREAD

**Issue by ZachCutler04** [visdesignlab/provenance-lib-core#38] opened 2020-05-27 09:42 UTC
Initial implementation of hybrid state and action based provenance. At first, only store the entire state every N actions. For every action, store the diff from the most recent state as well as the actual "action", that created the change, typically a function.

**Comment by kirangadhave** [comment] 2020-05-27 22:38
Duplicate of #36

**Comment by kirangadhave** [comment] 2020-05-27 22:38
Closing this to keep discussion centered around #36

**Closed by kirangadhave** 2020-05-27 22:38 UTC
